### PR TITLE
fix: Show if file has redirect setup in list view

### LINKED ISSUE #897: Indicate when a document is redirecting in the list view
**Description**
When a document has been unpublished // redirected, DA still indicates that a document is published. This has lead to some confusion for our authors on adobe.com. We should check if a redirectLocation has been applied and change the label accordingly
```js
"live": {
    "url": "https://main--project--org.aem.live/jp/products/redirected-story!!",
    ...
    "redirectLocation": "...", // <- should indicate there IS an existing published redirect
    "configRedirectLocation": "...",
    "permissions": [ ... ]
  },
```

Here's a mockup of how it could look changing the "PUBLISHED" label to "REDIRECT(ED)"
Image

### PR DESCRIPTION
**Pull request by chrischrischris**
If a file has a redirect setup for Publish, change wording to "Redirect" and include link to redirect location.

Fix #897 

Screenshot 2026-04-28 at 10 27 47 AM

### CODE REVIEW

File: blocks/browse/da-list-item/da-list-item.js [hunk 1]
```diff
@@ -288,26 +290,26 @@ export default class DaListItem extends LitElement {
...
-          href=${this._live?.url}
+          href=${this._live?.redirect || this._live?.url}
           target="_blank"
           aria-label="Open preview"
           @click=${this.showPreview}
           class="da-item-list-item-aem-btn">
           <div class="da-item-list-item-aem-icon ${this._live?.status === 200 ? 'is-active' : ''}"></div>
           <div class="da-aem-icon-details">
-            <p class="da-list-item-details-title">Published</p>
+            <p class="da-list-item-details-title">${this._live?.redirect ? 'Publish Redirect' : 'Published'}</p>
```
Comment (mokimo) [inline blocks/browse/da-list-item/da-list-item.js]:
```suggestion
            <p class="da-list-item-details-title">${this._live?.redirect ? 'Published Redirect' : 'Published'}</p>
```

**Review by mokimo — APPROVED** [review]

File: blocks/browse/da-list-item/da-list-item.js (hunk 1 above)
Comment (chrischrischris) [reply blocks/browse/da-list-item/da-list-item.js]: I kept the "ed" out as it forces line wrapping and (to me at least) sounds better in the present tense, but I'm open to either.

Screenshot 2026-04-28 at 10 03 19 AM

Comment (mokimo) [reply blocks/browse/da-list-item/da-list-item.js]: No that's fine if it was a concious decision 😁 

For me it was more an OCD/consistency thing, in the sense that
an article was 'published' so it's also a 'published redirect'

no hard opinion on it though, as long as it's indicated that it's a redirect in any form, its hopefully less confusing to authors!

Comment (chrischrischris) [reply blocks/browse/da-list-item/da-list-item.js]: Yeah agreed - I tweaked the css so it doesn't line wrap.  See new screenshot in desc

**Review by auniverseaway — APPROVED** [review]
