### PR TITLE
Do not enable contentEditable for readonly docs

### LINKED ISSUE #473: Reaonly document is editable
If I have a document that's readonly according to its ACL, I can still edit it in the DA editor. Modification won't be persisted, but it _appears_ that the document is edited.

This issue seems to have been introduced with https://github.com/adobe/da-live/commit/c17a025e76eacb08e8abc65c0b68b65d5e8ad7e5

The error can be observed in the Playwright tests, e.g. see this run: https://github.com/adobe/da-live/actions/runs/15827448838/job/44613178061

The easiest way to reproduce is by running the playwright tests locally. Like this:

in .../da-live/test/e2e run for (pwd provide the password for the `da-test@adobetest.com` user}:
```
$ TEST_PASSWORD='<pwd>' npx playwright test  --project=chromium tests/authenticated/acl_doc.spec.js --debug
```

Once the UI appears, step through it (with F10) until line 21 of acl_doc.spec.js:

Image
 

Then the screen will look like the attached screenshot, where you can see the 'readonly lock' but you can still edit text.

Image

### PR DESCRIPTION
**Pull request by chrischrischris**
Check the permissions to ensure user has write permissions on the document

Fixes #473

Note that the below urls require you to be logged in with the da-test@adobetest.com user

Before: https://main--da-live--adobe.hlx.live/edit#/da-testautomation/acltest/testdocs/doc_readonly
After: https://ccc473--da-live--adobe.hlx.live/edit#/da-testautomation/acltest/testdocs/doc_readonly

### CODE REVIEW

File: blocks/edit/prose/index.js [hunk 1]
```diff
@@ -179,16 +179,20 @@ function restoreCursorPosition(view) {
...
-  wsProvider.on('synced', (isSynced) => {
-    if (isSynced && !initialContentLoaded) {
-      const pm = document.querySelector('da-content')?.shadowRoot
-        .querySelector('da-editor')?.shadowRoot.querySelector('.ProseMirror');
-      if (pm) pm.contentEditable = 'true';
-
-      initialContentLoaded = true;
+  const handleSynced = (isSynced) => {
+    if (isSynced) {
+      const permissions = document.querySelector('da-title').permissions || [];
```
Comment (auniverseaway) [inline blocks/edit/prose/index.js:184]: The permissions are already passed into `initProse` you can pass them into `addSycnedListener`.

**Comment by kptdobe** [comment]
This is what I see, not sure if this is expected... (not new, same on `main` and on current branch)

image

**Comment by chrischrischris** [comment]
@kptdobe Sorry about that - forgot to mention that you need to be logged in with the da-test@adobetest.com user in order to test the page.

**Review by auniverseaway — APPROVED** [review]
